### ISSUE TITLE
For working on Windows

### ISSUE THREAD

**Issue by nlyamada** [chocolate-icecream/pyigor#1]
Thanks for the useful package for communication between Python and Igor. I'm having fun using it!
Before running the package on Windows, I had to make the following changes to pyigor.py.

- Line 16: I changed the path to the executable. Although the comment says that this part is OS dependent code, it seems easier for users to change the code if both paths are shown. Or it might be better for users to set the path manually for ease of use.
```
#path_candidates = glob.glob("/Applications/Igor Pro*/Igor64.app/Contents/MacOS/Igor64")
path_candidates = glob.glob("C:\Program Files\WaveMetrics\Igor Pro 8 Folder\IgorBinaries_x64\Igor64.exe")
```
- Line 160: I changed the argument from the sequence to the text of the full path because the Windows OS automatically inserts the escape sequence before the double quotes. If this code works on Mac OS, the modified way may be better for compatibility.
```
#subprocess.run([self._executable_path, "-Q", "-X", command])
temp = subprocess.list2cmdline([self._executable_path, "-Q", "-X"])
temp = f"{temp} {command}"
subprocess.run(temp)
```
- Line 170: The script never works without replacing "==" with "=" (I think this is also true for Mac OS).
```
#self._registered_functions[f.__name__] == f
self._registered_functions[f.__name__] = f
```

This is fine for me because I've already fixed the problems, but other users would appreciate an official fix. Could you consider it?

**Comment by chocolate-icecream** [comment]
Thanks for your help and the Windows tips. I'm happy to hear you're enjoying the package! I'll make those changes and fix the bug soon.
