### ISSUE TITLE
Problem finding the correct path in windows

### ISSUE THREAD

**Issue by melfon** [chocolate-icecream/pyigor#2]
A backslash is missing in the generated windows path.

Changing line 25 will solve it:

"windows": os.path.join("C:\\", "Program Files", "WaveMetrics", "Igor Pro * Folder", "IgorBinaries_x64", "Igor64.exe")}

**Comment by melfon** [comment]
In the code I put in a double backslash. That does not show up above.

**Comment by chocolate-icecream** [comment]
Thank you for pointing out the issue with the Windows path. I appreciate your suggestion. I will update the code accordingly.
